/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalystRouteImport } from './routes/analyst'
import { Route as GlossaryRouteImport } from './routes/glossary'
import { Route as HomeRouteImport } from './routes/home'
import { Route as InstitutionalRouteImport } from './routes/institutional'
import { Route as LeaderboardsRouteImport } from './routes/leaderboards'
import { Route as MapRouteImport } from './routes/map'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RankedRouteImport } from './routes/ranked'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as AcademyIndexRouteImport } from './routes/academy.index'
import { Route as AcademyLessonIdRouteImport } from './routes/academy.$lessonId'
import { Route as LevelsStrategyIdRouteImport } from './routes/levels.$strategyId'
import { Route as PlayLevelIdRouteImport } from './routes/play.$levelId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalystRoute = AnalystRouteImport.update({
  id: '/analyst',
  path: '/analyst',
  getParentRoute: () => rootRouteImport,
} as any)
const GlossaryRoute = GlossaryRouteImport.update({
  id: '/glossary',
  path: '/glossary',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const InstitutionalRoute = InstitutionalRouteImport.update({
  id: '/institutional',
  path: '/institutional',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardsRoute = LeaderboardsRouteImport.update({
  id: '/leaderboards',
  path: '/leaderboards',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RankedRoute = RankedRouteImport.update({
  id: '/ranked',
  path: '/ranked',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyIndexRoute = AcademyIndexRouteImport.update({
  id: '/academy/',
  path: '/academy/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyLessonIdRoute = AcademyLessonIdRouteImport.update({
  id: '/academy/$lessonId',
  path: '/academy/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)
const LevelsStrategyIdRoute = LevelsStrategyIdRouteImport.update({
  id: '/levels/$strategyId',
  path: '/levels/$strategyId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayLevelIdRoute = PlayLevelIdRouteImport.update({
  id: '/play/$levelId',
  path: '/play/$levelId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analyst': typeof AnalystRoute
  '/glossary': typeof GlossaryRoute
  '/home': typeof HomeRoute
  '/institutional': typeof InstitutionalRoute
  '/leaderboards': typeof LeaderboardsRoute
  '/map': typeof MapRoute
  '/practice': typeof PracticeRoute
  '/profile': typeof ProfileRoute
  '/ranked': typeof RankedRoute
  '/settings': typeof SettingsRoute
  '/academy/$lessonId': typeof AcademyLessonIdRoute
  '/levels/$strategyId': typeof LevelsStrategyIdRoute
  '/play/$levelId': typeof PlayLevelIdRoute
  '/academy/': typeof AcademyIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analyst': typeof AnalystRoute
  '/glossary': typeof GlossaryRoute
  '/home': typeof HomeRoute
  '/institutional': typeof InstitutionalRoute
  '/leaderboards': typeof LeaderboardsRoute
  '/map': typeof MapRoute
  '/practice': typeof PracticeRoute
  '/profile': typeof ProfileRoute
  '/ranked': typeof RankedRoute
  '/settings': typeof SettingsRoute
  '/academy/$lessonId': typeof AcademyLessonIdRoute
  '/levels/$strategyId': typeof LevelsStrategyIdRoute
  '/play/$levelId': typeof PlayLevelIdRoute
  '/academy': typeof AcademyIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analyst': typeof AnalystRoute
  '/glossary': typeof GlossaryRoute
  '/home': typeof HomeRoute
  '/institutional': typeof InstitutionalRoute
  '/leaderboards': typeof LeaderboardsRoute
  '/map': typeof MapRoute
  '/practice': typeof PracticeRoute
  '/profile': typeof ProfileRoute
  '/ranked': typeof RankedRoute
  '/settings': typeof SettingsRoute
  '/academy/$lessonId': typeof AcademyLessonIdRoute
  '/levels/$strategyId': typeof LevelsStrategyIdRoute
  '/play/$levelId': typeof PlayLevelIdRoute
  '/academy/': typeof AcademyIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analyst'
    | '/glossary'
    | '/home'
    | '/institutional'
    | '/leaderboards'
    | '/map'
    | '/practice'
    | '/profile'
    | '/ranked'
    | '/settings'
    | '/academy/$lessonId'
    | '/levels/$strategyId'
    | '/play/$levelId'
    | '/academy/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analyst'
    | '/glossary'
    | '/home'
    | '/institutional'
    | '/leaderboards'
    | '/map'
    | '/practice'
    | '/profile'
    | '/ranked'
    | '/settings'
    | '/academy/$lessonId'
    | '/levels/$strategyId'
    | '/play/$levelId'
    | '/academy'
  id:
    | '__root__'
    | '/'
    | '/analyst'
    | '/glossary'
    | '/home'
    | '/institutional'
    | '/leaderboards'
    | '/map'
    | '/practice'
    | '/profile'
    | '/ranked'
    | '/settings'
    | '/academy/$lessonId'
    | '/levels/$strategyId'
    | '/play/$levelId'
    | '/academy/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalystRoute: typeof AnalystRoute
  GlossaryRoute: typeof GlossaryRoute
  HomeRoute: typeof HomeRoute
  InstitutionalRoute: typeof InstitutionalRoute
  LeaderboardsRoute: typeof LeaderboardsRoute
  MapRoute: typeof MapRoute
  PracticeRoute: typeof PracticeRoute
  ProfileRoute: typeof ProfileRoute
  RankedRoute: typeof RankedRoute
  SettingsRoute: typeof SettingsRoute
  AcademyLessonIdRoute: typeof AcademyLessonIdRoute
  LevelsStrategyIdRoute: typeof LevelsStrategyIdRoute
  PlayLevelIdRoute: typeof PlayLevelIdRoute
  AcademyIndexRoute: typeof AcademyIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyst': {
      id: '/analyst'
      path: '/analyst'
      fullPath: '/analyst'
      preLoaderRoute: typeof AnalystRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glossary': {
      id: '/glossary'
      path: '/glossary'
      fullPath: '/glossary'
      preLoaderRoute: typeof GlossaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/institutional': {
      id: '/institutional'
      path: '/institutional'
      fullPath: '/institutional'
      preLoaderRoute: typeof InstitutionalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboards': {
      id: '/leaderboards'
      path: '/leaderboards'
      fullPath: '/leaderboards'
      preLoaderRoute: typeof LeaderboardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranked': {
      id: '/ranked'
      path: '/ranked'
      fullPath: '/ranked'
      preLoaderRoute: typeof RankedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy/': {
      id: '/academy/'
      path: '/academy'
      fullPath: '/academy/'
      preLoaderRoute: typeof AcademyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy/$lessonId': {
      id: '/academy/$lessonId'
      path: '/academy/$lessonId'
      fullPath: '/academy/$lessonId'
      preLoaderRoute: typeof AcademyLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/levels/$strategyId': {
      id: '/levels/$strategyId'
      path: '/levels/$strategyId'
      fullPath: '/levels/$strategyId'
      preLoaderRoute: typeof LevelsStrategyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/$levelId': {
      id: '/play/$levelId'
      path: '/play/$levelId'
      fullPath: '/play/$levelId'
      preLoaderRoute: typeof PlayLevelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalystRoute: AnalystRoute,
  GlossaryRoute: GlossaryRoute,
  HomeRoute: HomeRoute,
  InstitutionalRoute: InstitutionalRoute,
  LeaderboardsRoute: LeaderboardsRoute,
  MapRoute: MapRoute,
  PracticeRoute: PracticeRoute,
  ProfileRoute: ProfileRoute,
  RankedRoute: RankedRoute,
  SettingsRoute: SettingsRoute,
  AcademyLessonIdRoute: AcademyLessonIdRoute,
  LevelsStrategyIdRoute: LevelsStrategyIdRoute,
  PlayLevelIdRoute: PlayLevelIdRoute,
  AcademyIndexRoute: AcademyIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
